#!/usr/bin/env python3
"""Generate internal/authz/catalogue_gen.go from the derived permission set.

Run after scripts/derive-permissions.py, which reads the router and writes
permissions.json. The Go file it emits is what the running service consults to
decide which permission a request needs, and what it refuses to start without.

    python3 scripts/derive-permissions-routes.py
    python3 scripts/derive-permissions.py
    python3 scripts/generate-authz-catalogue.py > services/api/internal/authz/catalogue_gen.go
"""
import json
import sys

SCRATCH = "/private/tmp/claude-501/-Users-sudipto-Desktop-projects-npdms/6795f28e-4b8d-4986-a2ad-60802678b8e5/scratchpad"
perms = json.load(open(f"{SCRATCH}/permissions.json"))

pairs = []
for key in sorted(perms):
    for route in perms[key]["routes"]:
        pairs.append((route, key))
pairs.sort()

dupes = [r for r, _ in pairs if [x for x, _ in pairs].count(r) > 1]
if dupes:
    sys.exit(f"a route maps to more than one permission: {sorted(set(dupes))[:5]}")

print('''// Code generated by scripts/generate-authz-catalogue.py. DO NOT EDIT.
//
// Which permission each route requires. Derived from the router itself, so
// this file and main.go cannot drift apart without the service refusing to
// start: VerifyRoutes walks every registered route at boot and panics on one
// that is not named here.
//
// To regenerate after adding a route:
//
//     python3 scripts/derive-permissions-routes.py
//     python3 scripts/derive-permissions.py
//     python3 scripts/generate-authz-catalogue.py > services/api/internal/authz/catalogue_gen.go
//
// A new permission also needs a row in the permissions table; add it to a
// migration, or the grid an administrator sees will not offer it.

package authz

// RoutePermissions maps "METHOD /path" — the gin route pattern, placeholders
// and all — to the permission a caller must hold.
var RoutePermissions = map[string]string{''')
for route, key in pairs:
    print(f'\t{json.dumps(route)}: {json.dumps(key)},')
print("}")

print('''
// Unauthenticated routes. They carry no permission because there is no
// officer to check one against: liveness probes, the API contract, signing in,
// and the citizen-facing portal, which is reached without an account at all.
var PublicRoutes = map[string]bool{''')
public = [
    "GET /health", "GET /ready", "GET /openapi.yaml",
    "POST /api/v1/auth/login", "POST /api/v1/auth/refresh", "POST /api/v1/auth/logout",
]
for r in public:
    print(f'\t{json.dumps(r)}: true,')
print("}")

print('''
// PublicPrefixes are route trees reached without signing in. The citizen
// portal is the whole of it: a complaint, a missing-person report or an FIR
// copy request is made by a member of the public.
var PublicPrefixes = []string{
	"/api/v1/public/",
}''')
