#!/usr/bin/env python3
"""Generate internal/authz/catalogue_gen.go from the permissions table.

The database is the source of truth, not main.go. It was main.go once — the
original catalogue was derived by reading the rank guard on every route — but
those guards are gone now that permissions decide, so there is nothing left in
the router to read. What remains is the permissions table, where every
capability is a row and every row lists the routes it covers.

That also makes adding a route a single, ordinary act: write the migration
that declares its permission, apply it, regenerate. If you forget, the service
refuses to start and names the route.

    DATABASE_URL=postgresql://sudipto@localhost:5432/npdms \\
      python3 scripts/generate-authz-catalogue.py \\
      > services/api/internal/authz/catalogue_gen.go
    gofmt -w services/api/internal/authz/catalogue_gen.go
"""
import json
import os
import subprocess
import sys

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://sudipto@localhost:5432/npdms")

result = subprocess.run(
    ["psql", DATABASE_URL, "-qAt", "-v", "ON_ERROR_STOP=1", "-c",
     "SELECT key, unnest(routes) FROM permissions ORDER BY 2, 1"],
    capture_output=True, text=True)
if result.returncode != 0:
    sys.exit(f"reading the permissions table failed:\n{result.stderr.strip()}")

pairs = []
for line in result.stdout.strip().split("\n"):
    if not line.strip():
        continue
    key, route = line.split("|", 1)
    pairs.append((route.strip(), key.strip()))

if len(pairs) < 500:
    sys.exit(f"only {len(pairs)} routes found; the permissions table looks unapplied")

seen = {}
for route, key in pairs:
    if route in seen and seen[route] != key:
        sys.exit(f"{route} is claimed by both {seen[route]} and {key}; "
                 "a route must need exactly one permission")
    seen[route] = key

print('''// Code generated by scripts/generate-authz-catalogue.py. DO NOT EDIT.
//
// Which permission each route requires, read out of the permissions table.
// The database is the source of truth: a capability is a row there, and the
// row lists the routes it covers.
//
// To add a route: declare its permission in a migration, apply it, then
//
//     DATABASE_URL=... python3 scripts/generate-authz-catalogue.py \\
//       > services/api/internal/authz/catalogue_gen.go
//     gofmt -w services/api/internal/authz/catalogue_gen.go
//
// Forgetting is not silent. VerifyRoutes walks every registered route at
// startup and refuses to run with one that is not named here.

package authz

// RoutePermissions maps "METHOD /path" — the gin route pattern, placeholders
// and all — to the permission a caller must hold.
var RoutePermissions = map[string]string{''')
for route in sorted(seen):
    print(f'\t{json.dumps(route)}: {json.dumps(seen[route])},')
print("}")

print('''
// Unauthenticated routes. They carry no permission because there is no
// officer to check one against: liveness probes, the API contract, signing in,
// and the citizen-facing portal, which is reached without an account at all.
var PublicRoutes = map[string]bool{''')
for r in ["GET /health", "GET /ready", "GET /openapi.yaml",
          "POST /api/v1/auth/login", "POST /api/v1/auth/refresh", "POST /api/v1/auth/logout"]:
    print(f'\t{json.dumps(r)}: true,')
print("}")

print('''
// PublicPrefixes are route trees reached without signing in. The citizen
// portal is the whole of it: a complaint, a missing-person report or an FIR
// copy request is made by a member of the public.
var PublicPrefixes = []string{
	"/api/v1/public/",
}''')
